name: 'MinedMap'
on: ['push', 'pull_request', 'workflow_dispatch']

jobs:
  viewer:
    name: 'Package viewer'
    runs-on: 'ubuntu-20.04'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - name: 'Get version'
        id: 'tag'
        run: |
          set -o pipefail
          #git fetch --prune --unshallow --tags -f
          echo "tag=$(git describe --abbrev=7 --match='v*' | sed 's/^v//')" >> $GITHUB_OUTPUT

      - name: 'Install'
        run: |
          pkgdir='build/pkg/MinedMap-${{ steps.tag.outputs.tag }}-viewer'
          mkdir -p "$pkgdir"
          cp -r viewer/* "$pkgdir"/

      - name: 'Archive'
        uses: 'actions/upload-artifact@v3'
        with:
          name: 'MinedMap-${{ steps.tag.outputs.tag }}-viewer'
          path: 'build/pkg'
